name: CI

on: [push, workflow_dispatch]

jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up
        uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.11
      - name: Build and Test
        run: |
          sbt -v +test
